import './globals.css'
import styles from '@/app/page.module.css';
import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
    <header className={styles.header}>
      <Link href="/">Home</Link>
      <a
        href="https://www.kernex.io"
        target="_blank"
        rel="noopener noreferrer"
        className={styles.logoContainer}
      >
        Powered By{' '}
        <img
          src="https://www.kernex.io/logo.png"
          alt="Kernex Logo"
          width={100}
          className={styles.logo}
        />
      </a>
    </header>
    <main className={styles.main}>
      {children}
    </main>
    </body>
    </html>
  )
}
